language: cpp

before_install:
  - chmod -R 777 *
  - tools/ci/before-install.sh

install:
  - tools/ci/install.sh
  
before_deploy: "tar cvfz release.tar.gz build/"  
deploy:
  provider: releases
  api_key:
    secure: "NLmDvcCaKqWrgp6CBFueKg1qUjwIWCpioGdsUNHuImPclCv0wSOT2mneJsEnqB78AXj+e53MOCN9xxJA1XRuiJTyt2GhsWo4oWzZzr1Nk9FH82rMV2f97njm6VXQTm19DKfyEOb3L4xRs8dTm7rT+uqNy53XY6sShtPLPDpLL3HgkvhPIYLWhSuNYHbKnJXEA1BJwgOqd/3iknNXM6humu6AB0ykAcdfs6jI1gs7lI5bBNrAGpOvubrD2y5XX9WPZN/N7zxflV5ffzmGgYdcHMHLBm8k9Cztgc/u/PJb+JEDLp5GLsY1u5e6cGk8SuK1Bk9F9Oiz5aeE39Drwv9nNs1U28xd8mYRMDhpiuKP0kwNsiX3ws6/CxtwPDHI6WrnlyzkGJY1RdvuRTyU69CLNxZi7TbOEXt3zdbR8asXfoyFCOTJXnUqXXGiZFi8YcfyfqlX/BUds9gkOCVYJIyvPC5I2SVxJRczXa05dWZq8p+9t95cuyNp+JXTiJtWluTCJX82LE6cxwKAMgyYe3UwY8rQxgq3SogaIkCChL5DSN76VCeI3KvGUgzMCxwf/bd/Asq7Pd3IeS/Ke9e+vk/UCeBI9uqWhNGJvGV6AI1WrH9Id1PCEE5lyqectpauQPtOcD5MEQLpHGITGbvSwyrL4xWVKe+gzlPJQioo6SoMvZE="
  file: "release.tar.gz"
  skip_cleanup: true
  on:
    tags: true

script:
  - tools/ci/build.sh

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: OGRE_VERSION=1.9

    - os: linux
      dist: trusty
      compiler: clang
      env: OGRE_VERSION=1.9